name: semantic-pr
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            chore
            refactor
            test
            ci
          requireScope: false
          # Caso queira permitir 'revert: ...' em títulos de PR, descomente:
          # validateSingleCommit: false
